# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Wed Apr 29 07:49:02 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 734)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.datacenterButton = QtGui.QRadioButton(self.centralwidget)
        self.datacenterButton.setObjectName("datacenterButton")
        self.gridLayout.addWidget(self.datacenterButton, 3, 1, 1, 1)
        self.brokerButton = QtGui.QRadioButton(self.centralwidget)
        self.brokerButton.setObjectName("brokerButton")
        self.gridLayout.addWidget(self.brokerButton, 3, 2, 1, 1)
        self.vmButton = QtGui.QRadioButton(self.centralwidget)
        self.vmButton.setObjectName("vmButton")
        self.gridLayout.addWidget(self.vmButton, 3, 3, 1, 1)
        self.hostButton = QtGui.QRadioButton(self.centralwidget)
        self.hostButton.setObjectName("hostButton")
        self.gridLayout.addWidget(self.hostButton, 3, 0, 1, 1)
        self.cloudletButton = QtGui.QRadioButton(self.centralwidget)
        self.cloudletButton.setObjectName("cloudletButton")
        self.gridLayout.addWidget(self.cloudletButton, 4, 0, 1, 1)
        self.outputButton = QtGui.QRadioButton(self.centralwidget)
        self.outputButton.setObjectName("outputButton")
        self.gridLayout.addWidget(self.outputButton, 4, 1, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.hostPage = QtGui.QWidget()
        self.hostPage.setObjectName("hostPage")
        self.gridLayout_2 = QtGui.QGridLayout(self.hostPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hostAdd = QtGui.QPushButton(self.hostPage)
        self.hostAdd.setObjectName("hostAdd")
        self.gridLayout_2.addWidget(self.hostAdd, 3, 0, 1, 1)
        self.hostDelete = QtGui.QPushButton(self.hostPage)
        self.hostDelete.setObjectName("hostDelete")
        self.gridLayout_2.addWidget(self.hostDelete, 3, 1, 1, 1)
        self.hostTable = QtGui.QTableWidget(self.hostPage)
        self.hostTable.setObjectName("hostTable")
        self.hostTable.setColumnCount(9)
        self.hostTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.hostTable.setHorizontalHeaderItem(8, item)
        self.gridLayout_2.addWidget(self.hostTable, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.hostPage)
        self.datacenterPage = QtGui.QWidget()
        self.datacenterPage.setObjectName("datacenterPage")
        self.gridLayout_6 = QtGui.QGridLayout(self.datacenterPage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.datacenterDelete = QtGui.QPushButton(self.datacenterPage)
        self.datacenterDelete.setObjectName("datacenterDelete")
        self.gridLayout_6.addWidget(self.datacenterDelete, 1, 1, 1, 1)
        self.datacenterAdd = QtGui.QPushButton(self.datacenterPage)
        self.datacenterAdd.setObjectName("datacenterAdd")
        self.gridLayout_6.addWidget(self.datacenterAdd, 1, 0, 1, 1)
        self.datacenterTable = QtGui.QTableWidget(self.datacenterPage)
        self.datacenterTable.setObjectName("datacenterTable")
        self.datacenterTable.setColumnCount(3)
        self.datacenterTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.datacenterTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.datacenterTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.datacenterTable.setHorizontalHeaderItem(2, item)
        self.gridLayout_6.addWidget(self.datacenterTable, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.datacenterPage)
        self.brokerPage = QtGui.QWidget()
        self.brokerPage.setObjectName("brokerPage")
        self.gridLayout_8 = QtGui.QGridLayout(self.brokerPage)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.brokerAdd = QtGui.QPushButton(self.brokerPage)
        self.brokerAdd.setObjectName("brokerAdd")
        self.gridLayout_8.addWidget(self.brokerAdd, 1, 0, 1, 1)
        self.brokerDelete = QtGui.QPushButton(self.brokerPage)
        self.brokerDelete.setObjectName("brokerDelete")
        self.gridLayout_8.addWidget(self.brokerDelete, 1, 1, 1, 1)
        self.brokerTable = QtGui.QTableWidget(self.brokerPage)
        self.brokerTable.setObjectName("brokerTable")
        self.brokerTable.setColumnCount(2)
        self.brokerTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.brokerTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.brokerTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_8.addWidget(self.brokerTable, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.brokerPage)
        self.vmPage = QtGui.QWidget()
        self.vmPage.setObjectName("vmPage")
        self.gridLayout_9 = QtGui.QGridLayout(self.vmPage)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.vmTable = QtGui.QTableWidget(self.vmPage)
        self.vmTable.setObjectName("vmTable")
        self.vmTable.setColumnCount(9)
        self.vmTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(8, item)
        self.gridLayout_9.addWidget(self.vmTable, 0, 0, 1, 2)
        self.vmAdd = QtGui.QPushButton(self.vmPage)
        self.vmAdd.setObjectName("vmAdd")
        self.gridLayout_9.addWidget(self.vmAdd, 1, 0, 1, 1)
        self.vmDelete = QtGui.QPushButton(self.vmPage)
        self.vmDelete.setObjectName("vmDelete")
        self.gridLayout_9.addWidget(self.vmDelete, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.vmPage)
        self.cloudletPage = QtGui.QWidget()
        self.cloudletPage.setObjectName("cloudletPage")
        self.gridLayout_10 = QtGui.QGridLayout(self.cloudletPage)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.cloudletTable = QtGui.QTableWidget(self.cloudletPage)
        self.cloudletTable.setObjectName("cloudletTable")
        self.cloudletTable.setColumnCount(7)
        self.cloudletTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cloudletTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cloudletTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cloudletTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.cloudletTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.cloudletTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.cloudletTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.cloudletTable.setHorizontalHeaderItem(6, item)
        self.gridLayout_10.addWidget(self.cloudletTable, 0, 0, 1, 2)
        self.cloudletDelete = QtGui.QPushButton(self.cloudletPage)
        self.cloudletDelete.setObjectName("cloudletDelete")
        self.gridLayout_10.addWidget(self.cloudletDelete, 1, 1, 1, 1)
        self.cloudletAdd = QtGui.QPushButton(self.cloudletPage)
        self.cloudletAdd.setObjectName("cloudletAdd")
        self.gridLayout_10.addWidget(self.cloudletAdd, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.cloudletPage)
        self.outputPage = QtGui.QWidget()
        self.outputPage.setObjectName("outputPage")
        self.horizontalLayout = QtGui.QHBoxLayout(self.outputPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outputBox = QtGui.QTextEdit(self.outputPage)
        self.outputBox.setObjectName("outputBox")
        self.horizontalLayout.addWidget(self.outputBox)
        self.stackedWidget.addWidget(self.outputPage)
        self.errorPage = QtGui.QWidget()
        self.errorPage.setObjectName("errorPage")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.errorPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.errorBox = QtGui.QTextEdit(self.errorPage)
        self.errorBox.setObjectName("errorBox")
        self.horizontalLayout_2.addWidget(self.errorBox)
        self.stackedWidget.addWidget(self.errorPage)
        self.graphPage = QtGui.QWidget()
        self.graphPage.setObjectName("graphPage")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.graphPage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget.addWidget(self.graphPage)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 4)
        self.errorButton = QtGui.QRadioButton(self.centralwidget)
        self.errorButton.setObjectName("errorButton")
        self.gridLayout.addWidget(self.errorButton, 4, 2, 1, 1)
        self.graphButton = QtGui.QRadioButton(self.centralwidget)
        self.graphButton.setObjectName("graphButton")
        self.gridLayout.addWidget(self.graphButton, 4, 3, 1, 1)
        self.previousButton = QtGui.QPushButton(self.centralwidget)
        self.previousButton.setObjectName("previousButton")
        self.gridLayout.addWidget(self.previousButton, 5, 0, 1, 1)
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuDistribution_Type = QtGui.QMenu(self.menuSimulation)
        self.menuDistribution_Type.setObjectName("menuDistribution_Type")
        self.menuSort_By = QtGui.QMenu(self.menuSimulation)
        self.menuSort_By.setObjectName("menuSort_By")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuGraph = QtGui.QMenu(self.menubar)
        self.menuGraph.setObjectName("menuGraph")
        self.menuScatter = QtGui.QMenu(self.menuGraph)
        self.menuScatter.setObjectName("menuScatter")
        self.menuBar = QtGui.QMenu(self.menuGraph)
        self.menuBar.setObjectName("menuBar")
        self.menuLine = QtGui.QMenu(self.menuGraph)
        self.menuLine.setObjectName("menuLine")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionDuplicate = QtGui.QAction(MainWindow)
        self.actionDuplicate.setObjectName("actionDuplicate")
        self.actionInsertRow = QtGui.QAction(MainWindow)
        self.actionInsertRow.setObjectName("actionInsertRow")
        self.actionNextPage = QtGui.QAction(MainWindow)
        self.actionNextPage.setObjectName("actionNextPage")
        self.actionPreviousPage = QtGui.QAction(MainWindow)
        self.actionPreviousPage.setObjectName("actionPreviousPage")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionNormal = QtGui.QAction(MainWindow)
        self.actionNormal.setCheckable(True)
        self.actionNormal.setObjectName("actionNormal")
        self.actionPoisson = QtGui.QAction(MainWindow)
        self.actionPoisson.setCheckable(True)
        self.actionPoisson.setObjectName("actionPoisson")
        self.actionChiSquare = QtGui.QAction(MainWindow)
        self.actionChiSquare.setCheckable(True)
        self.actionChiSquare.setObjectName("actionChiSquare")
        self.actionGamma = QtGui.QAction(MainWindow)
        self.actionGamma.setCheckable(True)
        self.actionGamma.setObjectName("actionGamma")
        self.actionExponential = QtGui.QAction(MainWindow)
        self.actionExponential.setCheckable(True)
        self.actionExponential.setObjectName("actionExponential")
        self.actionSCL = QtGui.QAction(MainWindow)
        self.actionSCL.setCheckable(True)
        self.actionSCL.setObjectName("actionSCL")
        self.actionSML = QtGui.QAction(MainWindow)
        self.actionSML.setCheckable(True)
        self.actionSML.setObjectName("actionSML")
        self.actionSML2 = QtGui.QAction(MainWindow)
        self.actionSML2.setCheckable(True)
        self.actionSML2.setObjectName("actionSML2")
        self.actionMarkov = QtGui.QAction(MainWindow)
        self.actionMarkov.setCheckable(True)
        self.actionMarkov.setObjectName("actionMarkov")
        self.actionCloudletID = QtGui.QAction(MainWindow)
        self.actionCloudletID.setCheckable(True)
        self.actionCloudletID.setObjectName("actionCloudletID")
        self.actionVmID = QtGui.QAction(MainWindow)
        self.actionVmID.setCheckable(True)
        self.actionVmID.setObjectName("actionVmID")
        self.actionStartTime = QtGui.QAction(MainWindow)
        self.actionStartTime.setCheckable(True)
        self.actionStartTime.setObjectName("actionStartTime")
        self.actionFinishTime = QtGui.QAction(MainWindow)
        self.actionFinishTime.setCheckable(True)
        self.actionFinishTime.setObjectName("actionFinishTime")
        self.actionSubmissionTime = QtGui.QAction(MainWindow)
        self.actionSubmissionTime.setCheckable(True)
        self.actionSubmissionTime.setObjectName("actionSubmissionTime")
        self.actionToggleLogs = QtGui.QAction(MainWindow)
        self.actionToggleLogs.setCheckable(True)
        self.actionToggleLogs.setObjectName("actionToggleLogs")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExit)
        self.menuDistribution_Type.addAction(self.actionNormal)
        self.menuDistribution_Type.addAction(self.actionPoisson)
        self.menuDistribution_Type.addAction(self.actionChiSquare)
        self.menuDistribution_Type.addAction(self.actionGamma)
        self.menuDistribution_Type.addAction(self.actionExponential)
        self.menuDistribution_Type.addAction(self.actionMarkov)
        self.menuSort_By.addAction(self.actionCloudletID)
        self.menuSort_By.addAction(self.actionVmID)
        self.menuSort_By.addAction(self.actionStartTime)
        self.menuSort_By.addAction(self.actionFinishTime)
        self.menuSort_By.addAction(self.actionSubmissionTime)
        self.menuSimulation.addAction(self.actionRun)
        self.menuSimulation.addAction(self.menuDistribution_Type.menuAction())
        self.menuSimulation.addAction(self.menuSort_By.menuAction())
        self.menuSimulation.addAction(self.actionToggleLogs)
        self.menuEdit.addAction(self.actionInsertRow)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionNextPage)
        self.menuEdit.addAction(self.actionPreviousPage)
        self.menuScatter.addAction(self.actionSCL)
        self.menuBar.addAction(self.actionSML)
        self.menuLine.addAction(self.actionSML2)
        self.menuGraph.addAction(self.menuBar.menuAction())
        self.menuGraph.addAction(self.menuLine.menuAction())
        self.menuGraph.addAction(self.menuScatter.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Datacenters page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterButton.setText(QtGui.QApplication.translate("MainWindow", "Datacenters", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Brokers page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerButton.setText(QtGui.QApplication.translate("MainWindow", "Brokers", None, QtGui.QApplication.UnicodeUTF8))
        self.vmButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Virtual Machines page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.vmButton.setText(QtGui.QApplication.translate("MainWindow", "Virtual Machines", None, QtGui.QApplication.UnicodeUTF8))
        self.hostButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Hosts page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hostButton.setText(QtGui.QApplication.translate("MainWindow", "Hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Cloudlets page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletButton.setText(QtGui.QApplication.translate("MainWindow", "Cloudlets", None, QtGui.QApplication.UnicodeUTF8))
        self.outputButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Output page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.outputButton.setText(QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.hostAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Add a new host</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hostAdd.setText(QtGui.QApplication.translate("MainWindow", "Add Host", None, QtGui.QApplication.UnicodeUTF8))
        self.hostDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Delete host</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hostDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete Host", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "CPUs", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "MIPS", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Bandwidth", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "VM Scheduler", None, QtGui.QApplication.UnicodeUTF8))
        self.hostTable.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "Datacenter ID", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Remove Datacenter</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterDelete.setText(QtGui.QApplication.translate("MainWindow", "Remove Datacenter", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Add new Datacenter</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterAdd.setText(QtGui.QApplication.translate("MainWindow", "Add Datacenter", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.datacenterTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Cost Per Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Add new Broker</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerAdd.setText(QtGui.QApplication.translate("MainWindow", "Add Broker", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Remove broker</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerDelete.setText(QtGui.QApplication.translate("MainWindow", "Remove Broker", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.brokerTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "CPUs", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "MIPS", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Bandwidth", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Cloudlet Scheduler", None, QtGui.QApplication.UnicodeUTF8))
        self.vmTable.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "BrokerID", None, QtGui.QApplication.UnicodeUTF8))
        self.vmAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Add new Virtual Machine</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.vmAdd.setText(QtGui.QApplication.translate("MainWindow", "Add Virtual Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.vmDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Delete Virtual Machine</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.vmDelete.setText(QtGui.QApplication.translate("MainWindow", "Remove Virtual Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Host Attributes</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "CPUs", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Submission Time", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Broker ID", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "VM ID", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Remove Cloudlet</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletDelete.setText(QtGui.QApplication.translate("MainWindow", "Remove Cloudlet", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Add new Cloudlet</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudletAdd.setText(QtGui.QApplication.translate("MainWindow", "Add Cloudlet", None, QtGui.QApplication.UnicodeUTF8))
        self.errorButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Error page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.errorButton.setText(QtGui.QApplication.translate("MainWindow", "Error", None, QtGui.QApplication.UnicodeUTF8))
        self.graphButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Switch to Graph page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.graphButton.setText(QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Previous page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Next page</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDistribution_Type.setTitle(QtGui.QApplication.translate("MainWindow", "Distribution Type", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSort_By.setTitle(QtGui.QApplication.translate("MainWindow", "Sort By", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGraph.setTitle(QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.menuScatter.setTitle(QtGui.QApplication.translate("MainWindow", "Scatter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBar.setTitle(QtGui.QApplication.translate("MainWindow", "Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLine.setTitle(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate.setText(QtGui.QApplication.translate("MainWindow", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertRow.setText(QtGui.QApplication.translate("MainWindow", "Insert Row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextPage.setText(QtGui.QApplication.translate("MainWindow", "Next Page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousPage.setText(QtGui.QApplication.translate("MainWindow", "Previous Page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormal.setText(QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPoisson.setText(QtGui.QApplication.translate("MainWindow", "Poisson", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChiSquare.setText(QtGui.QApplication.translate("MainWindow", "Chi-Square", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGamma.setText(QtGui.QApplication.translate("MainWindow", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExponential.setText(QtGui.QApplication.translate("MainWindow", "Exponential", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSCL.setText(QtGui.QApplication.translate("MainWindow", "Show connecting line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSML.setText(QtGui.QApplication.translate("MainWindow", "Show mean line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSML2.setText(QtGui.QApplication.translate("MainWindow", "Show mean line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarkov.setText(QtGui.QApplication.translate("MainWindow", "Markov", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloudletID.setText(QtGui.QApplication.translate("MainWindow", "Cloudlet ID", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVmID.setText(QtGui.QApplication.translate("MainWindow", "VM ID", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartTime.setText(QtGui.QApplication.translate("MainWindow", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFinishTime.setText(QtGui.QApplication.translate("MainWindow", "Finish Time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubmissionTime.setText(QtGui.QApplication.translate("MainWindow", "Submission Time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggleLogs.setText(QtGui.QApplication.translate("MainWindow", "Toggle logs", None, QtGui.QApplication.UnicodeUTF8))

